language: python
cache:
  - pip

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    # 3.7 issue https://github.com/travis-ci/travis-ci/issues/9069
    - python: 3.7
      env: TOXENV=py37
      sudo: true
      dist: xenial
    - python: pypy
      env: TOXENV=pypy

install:
  - pip install -U setuptools tox coveralls

script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then tox -e pep8,py27; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then tox -e pep8,py34; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then tox -e pep8,py35; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then tox -e pep8,py36; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then tox -e pep8,py37; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then tox -e pep8,pypy; fi

after_success:
  - coveralls
